@GestaoPedido.API_HostAddress = https://localhost:7181
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6IkFkbWluIiwibmFtZWlkIjoiOWNhY2JiYWQtZmNiNS00NDZkLTlkODAtYjRhMmRlYjZkMzljIiwibmJmIjoxNzUwNjExNTE0LCJleHAiOjE3NTA2MTUxMTQsImlhdCI6MTc1MDYxMTUxNCwiaXNzIjoiR2VzdGFvUGVkaWRvU2VydmVyIiwiYXVkIjoiR2VzdGFvUGVkaWRvQXBpIn0.4vGlopQA6FwVivEXXdXg3RNzfOaArQxZDNDCDvk9fg4

### Criar cliente
POST {{GestaoPedido.API_HostAddress}}/api/clientes
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "nome": "Maria da Silva",
  "documento": "12345678900"
}

###

### Buscar cliente por ID
GET {{GestaoPedido.API_HostAddress}}/api/clientes/00000000-0000-0000-0000-000000000000
Authorization: Bearer {{token}}
Accept: application/json

###

### Listar clientes (com paginação)
GET {{GestaoPedido.API_HostAddress}}/api/clientes?pagina=1&tamanhoPagina=10
Authorization: Bearer {{token}}
Accept: application/json

###
